clear all; clc; close all;
fprintf('Start at %s\n', datestr(now,'HH:MM:SS.FFF'))

catalogue = {
    'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h1_50st_20s\temp',...
    'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h2_50st_20s\temp',...
    'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h3_50st_20s\temp',...
    'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h4_50st_20s\temp',...
    'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h5_50st_20s\temp',...
    'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h6_50st_20s\temp',...
    'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h7_50st_20s\temp',...
    'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h8_50st_20s\temp',...
    'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h9_50st_20s\temp'};

% catalogue = {'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d1_h1_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d1_h2_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d1_h3_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d1_h4_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d1_h5_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d1_h6_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d1_h7_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d1_h8_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d1_h9_50st_20s\temp',...
%         'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d2_h1_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d2_h2_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d2_h3_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d2_h4_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d2_h5_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d2_h6_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d2_h7_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d2_h8_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d2_h9_50st_20s\temp',...
%         'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d3_h1_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d3_h2_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d3_h3_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d3_h4_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d3_h5_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d3_h6_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d3_h7_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d3_h8_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d3_h9_50st_20s\temp',...
%         'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d4_h1_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d4_h2_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d4_h3_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d4_h4_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d4_h5_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d4_h6_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d4_h7_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d4_h8_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d4_h9_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d5_h1_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d5_h2_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d5_h3_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d5_h4_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d5_h5_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d5_h6_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d5_h7_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d5_h8_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d5_h9_50st_20s\temp',...  
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d6_h1_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d6_h2_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d6_h3_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d6_h4_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d6_h5_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d6_h6_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d6_h7_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d6_h8_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d6_h9_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h1_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h2_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h3_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h4_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h5_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h6_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h7_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h8_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d7_h9_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d8_h1_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d8_h2_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d8_h3_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d8_h4_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d8_h5_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d8_h6_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d8_h7_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d8_h8_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d8_h9_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d9_h1_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d9_h2_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d9_h3_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d9_h4_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d9_h5_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d9_h6_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d9_h7_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d9_h8_50st_20s\temp',...
%     'C:\Users\agata\Documents\_POLSL\_IR3D\_IR3D_modele_new\ir3d\thermal_model_3D\results\20s\cylinder_s1_d9_h9_50st_20s\temp'};%,...
% %     'D:\ib_wymiana\_AS_\Projekty\IR3D\Symulacje-20201109T125210Z-001\Symulacje\cylinder_s1_d4_50st_20s\temp\',...
% %     'D:\ib_wymiana\_AS_\Projekty\IR3D\Symulacje-20201109T125210Z-001\Symulacje\cylinder_s1_d4_50st_20s\temp\',...
% %     'D:\ib_wymiana\_AS_\Projekty\IR3D\Symulacje-20201109T125210Z-001\Symulacje\cylinder_s1_d4_50st_20s\temp\',...
% %     'D:\ib_wymiana\_AS_\Projekty\IR3D\Symulacje-20201109T125210Z-001\Symulacje\cylinder_s1_d5_50st_20s\temp\',...
% %     'D:\ib_wymiana\_AS_\Projekty\IR3D\Symulacje-20201109T125210Z-001\Symulacje\cylinder_s1_d6_50st_20s\temp\',...
% %     'D:\ib_wymiana\_AS_\Projekty\IR3D\Symulacje-20201109T125210Z-001\Symulacje\cylinder_s1_d7_50st_20s\temp\',...
% %     'D:\ib_wymiana\_AS_\Projekty\IR3D\Symulacje-20201109T125210Z-001\Symulacje\cylinder_s1_d8_50st_20s\temp\',...
% %     'D:\ib_wymiana\_AS_\Projekty\IR3D\Symulacje-20201109T125210Z-001\Symulacje\cylinder_s1_d9_50st_20s\temp\',...
% %     'D:\ib_wymiana\_AS_\Projekty\IR3D\Symulacje-20201109T125210Z-001\Symulacje\cylinder_s1_d40_50st_20s\temp\',...
% %     };

for i = 1:numel(catalogue)
    A = dir([catalogue{i} '\*.mat']); % png
    no_images = length(A);
    
    sizex_mat=[]; sizey_mat =[];
    for k = 1:numel(A)
        ima = A(k).name;
        [sizex sizey] = size(imresize(load([catalogue{i} '\' ima]).I_temp, 0.3));
        sizex_mat = [sizex_mat; sizex]; sizey_mat = [sizey_mat; sizey];
    end
    
    sizex_max = max(sizex_mat(:));
    sizey_max = max(sizey_mat(:));

%     im = A(1).name;
%     Jim = load([catalogue{i} '\' im]);
%     Jim = Jim.I_temp;
%     Jim = imresize(Jim, 0.2);
%     [x y z] = size(Jim);
    rotation = 359;
    for j = 1:sizex_max %x
        ir3d(:,:,j) = singleSliceRecoTemp(catalogue{i}, A, no_images, j, sizex_max, sizey_max);
%         ir3d(:,:,j) = imrotate(BPI, -90);
        disp(['Iteration: ' num2str(j)])
    end
    ir3d = imresize3(ir3d, [100 100 50]);
    mkdir([catalogue{i} 'reco\'])
    splitit = split(catalogue{i}, '\');
    name_split = splitit(end-1);
    name = ['reco\' name_split{1} '.mat'];
    save([catalogue{i} name], 'ir3d');
    clear ir3d
end
fprintf('End at %s\n', datestr(now,'HH:MM:SS.FFF'))